ecom/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls', namespace='store')),
    path('cart/',include('cart.urls', namespace='cart')),
    path('payment/',include('payment.urls', namespace='payment')),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('payment-success', views.payment_success, name='payment-success'),
    path('payment-success', views.payment_success, name='payment-success'),
    path('checkout', views.checkout, name='checkout'),
    path('billing-info', views.billing_info, name='billing_info'),

]

ecom/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('update_user/', views.update_user, name='update_user'),
    path('update_info/', views.update_info, name='update_info'),
    path('update_password/', views.update_password, name='update_password'),
    path('products/<int:pk>/', views.product, name='product'),
    path('category/<str:category_name>/', views.category, name='category'),
    path('category_summary/', views.category_summary, name='category_summary'),
    path('search/', views.search, name='search'),
]

ecom/cart/models.py
from django.db import models

# Create your models here.

ecom/cart/views.py
from django.shortcuts import render, get_object_or_404
from .cart import Cart
from store.models import Product
from django.http import JsonResponse
from django.contrib import messages


# Create your views here.
def cart(request):
    cart = Cart(request)
    cart_products = cart.get_prods
    quantities = cart.get_quants
    totals = cart.cart_total()
    return render(request, 'cart/cart.html', {'cart_products': cart_products, 'quantities': quantities, 'totals': totals})



def cart_add(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':

        product_id = int(request.POST.get('product_id'))
        product_quantity = int(request.POST.get('product_quantity'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, quantity=product_quantity)

        cart_quantity = cart.__len__()
        response = JsonResponse({'Cart Quantity': cart_quantity})
        messages.success(request, "Item added to cart successfully")
        return response
    



def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':

        product_id = int(request.POST.get('product_id'))
        cart.delete(product=product_id)
        response = JsonResponse({'product': product_id})
        messages.success(request, "Item removed from cart successfully")
        return response

def cart_update(request):
    cart = Cart(request)
    if request.POST.get('action') == 'post':

        product_id = int(request.POST.get('product_id'))
        product_quantity = int(request.POST.get('product_quantity'))
        cart.update(product_id=product_id, quantity=product_quantity)
        response = JsonResponse({'quantity': product_quantity})
        messages.success(request, "Item updated in cart successfully")

        return response
        return redirect('cart:cart')

ecom/cart/templates/cart/cart.html
{% extends 'base.html' %}


{% block content %}

        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Shopping Cart</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Items in your cart</p>
                </div>
            </div>
        </header>
        <br/>
        <div class="container">
            
        {% if cart_products %}
        	{% for product in cart_products %}
        	
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{ product.image.url }}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <center>
        <h5 class="card-title">{{ product.name }}</h5>
        <br/>
        <p class="card-text justified">{{ product.description }}</p>
        
        {% if product.is_sale %}
        <div class="d-flex justify-content-center small text-warning mb-2">
                <div class="bi-star-fill"></div>
                &nbsp;&nbsp;Sale!&nbsp;&nbsp;
                <div class="bi-star-fill"></div>
                </div>

                <!-- Product price-->
                <strike>
                ${{ product.price }}
                </strike>
                &nbsp;
                ${{ product.sale_price }}



        {% else %}
            ${{ product.price }}
            
        {% endif %}
        <br/><br/>
        <div class="row justify-content-center">
    <div class="col-md-2">Quantity:</div>
                <div class="col-md-2">
                <select class="form-select form-select-sm" id="select{{product.id}}">
                  
            {% for key, value in quantities.items %}
                {% if key == product.id|slugify %}
            <option selected>{{ value }}</option>
                {% endif %}
            {% endfor %}
                           

                  <option value="1">1</option>
                  <option value="2">2</option>
                  <option value="3">3</option>
                  <option value="4">4</option>
                  <option value="5">5</option>
                </select>
                </div>
            </div>
            <br/><br/>
        <a href="{% url 'store:home' %}" class="btn btn-secondary">Home</a>
        <button type="button" data-index="{{product.id}}" class="btn btn-secondary update-cart">Update</button>
        <button type="button" data-index="{{product.id}}" class="btn btn-danger delete-product">Remove</button>

        </center>

      </div>
    </div>
  </div>
</div>

        	{% endfor %}
            <div align="right">

        
            <h3>Total: ${{ totals }}</h3>
            <a href="{% url 'payment:checkout' %}" class="btn btn-primary">Checkout</a>

            <br/>
        {% else %}
            <div class="text-center my-5">
                <h4>Your cart is empty</h4>
                <p>Looks like you haven't added anything to your cart yet.</p>
                <a href="{% url 'store:home' %}" class="btn btn-primary">Continue Shopping</a>
            </div>
        {% endif %}

        </div>



<script>
    $(document).on('click', '.update-cart', function(e) {  // #when its an id and . when its a class
        e.preventDefault();
        var productid = $(this).data('index');
        $.ajax({
            url: "{% url 'cart:cart_update' %}",
            type: "POST",
            data: {
                product_id: $(this).data('index'),
                product_quantity: $('#select' + productid + ' option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response) {
                location.reload(); // This will show cart quantity and product info in the browser console
            },
            error: function(xhr, errmsg, err) {
                // Handle error
            }
        });
    });

    $(document).on('click', '.delete-product', function(e) {  // #when its an id and . when its a class
        e.preventDefault();
        //var productid = $(this).data('index');
        $.ajax({
            url: "{% url 'cart:cart_delete' %}",
            type: "POST",
            data: {
                product_id: $(this).data('index'),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response) {
                location.reload(); // This will show cart quantity and product info in the browser console
            },
            error: function(xhr, errmsg, err) {
                // Handle error
            }
        });
    });
</script>

{% endblock %}