ecom/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/', views.cart_add, name='cart_add'),
    path('delete/', views.cart_delete, name='cart_delete'),
    path('update/', views.cart_update, name='cart_update'),
]

ecom/ecom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls', namespace='store')),
    path('cart/',include('cart.urls', namespace='cart')),
    path('payment/',include('payment.urls', namespace='payment')),  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('payment-success', views.payment_success, name='payment-success'),
    path('payment-success', views.payment_success, name='payment-success'),
    path('checkout', views.checkout, name='checkout'),
    path('billing-info', views.billing_info, name='billing_info'),

]

ecom/payment/models.py
from django.db import models
from django.contrib.auth.models import User
from store.models import Product, Profile
from django.db.models.signals import post_save


# Create your models here.
class ShippingAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    address_line1 = models.CharField(max_length=255)
    address_line2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100, blank=True)
    zipcode = models.CharField(max_length=20,blank=True)
    country = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Shipping Addresses"

    def __str__(self):
        return f"Shipping Address - {str(self.id)}"
    
    
def create_shipping(sender, instance, created, **kwargs):
    if created:
        user_shipping = ShippingAddress(user=instance)
        user_shipping.save()
post_save.connect(create_shipping, sender=User)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    full_name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    shipping_address = models.TextField(max_length=500, blank=True)
    amount_paid = models.DecimalField(max_digits=10, decimal_places=2)
    date_ordered= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order - {str(self.id)}"
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)    
    

    def __str__(self):
        return f"OrderItem - {str(self.id)}"

ecom/payment/forms.py
from django import forms

#from store.models import models
from .models import ShippingAddress 

class ShippingAddressForm(forms.ModelForm):
    user = forms.CharField(label="", max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'User Name'}))
    full_name = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Full Name'}))
    email = forms.EmailField(label="", widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email Address'}))
    address_line1 = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Address Line 1'}))
    address_line2 = forms.CharField(label="", required=False, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Address Line 2 (Optional)'}))
    city = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'City'}))
    state = forms.CharField(label="", required=False, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'State (Optional)'}))
    zipcode = forms.CharField(label="", required=False, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Zip Code (Optional)'}))
    country = forms.CharField(label="", widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Country'}))

    class Meta:
        model = ShippingAddress
        fields = ('user', 'full_name', 'email', 'address_line1', 'address_line2', 'city', 'state', 'zipcode', 'country')

        exclude = ['user'] 

ecom/payment/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from cart.cart import Cart
from payment.models import ShippingAddress
from .forms import ShippingAddressForm as ShippingForm
# Create your views here.
def checkout(request):
    cart = Cart(request)
    cart_products = cart.get_prods()
    quantities = cart.get_quants()
    totals = cart.cart_total()

    if request.user.is_authenticated:
        try:
            shipping_user = ShippingAddress.objects.get(user__id=request.user.id)
            shipping_form = ShippingForm(request.POST or None, instance=shipping_user)
        except ShippingAddress.DoesNotExist:
            shipping_form = ShippingForm(request.POST or None)
        return render(request, 'payment/checkout.html', {'cart_products': cart_products, 'quantities': quantities, 'totals': totals, 'shipping_form': shipping_form})

    else:
        shipping_form = ShippingForm(request.POST or None)
        return render(request, 'payment/checkout.html', {'cart_products': cart_products, 'quantities': quantities, 'totals': totals, 'shipping_form': shipping_form})

def payment_success(request):
    return render(request, 'payment/payment_success.html',{})

def billing_info(request):
    if request.method == 'POST':
        cart = Cart(request)
        cart_products = cart.get_prods()
        quantities = cart.get_quants()
        totals = cart.cart_total()
        shipping_form = ShippingForm(request.POST or None)
                
        return render(request, 'payment/billing_info.html', {'cart_products': cart_products, 'quantities': quantities, 'totals': totals, 'shipping_form': shipping_form})
    else:
        messages.error(request, "Invalid form submission. Please try again.")
        return redirect('store:home')
        

ecom/payment/templates/payment/billing_info.html
{% extends 'base.html' %}


{% block content %}

        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Billing Information</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Enter your payment information</p>
                </div>
            </div>
        </header>
        <br/>
        <div class="container">
            <div class="card">
  <div class="card-header">
    Order Summary
  </div>
  <div class="card-body">
    {% for product in cart_products %}
    {{ product.name}}
    {% if product.is_sale %}

        ${{ product.sale_price }}
    {% else %}
        {{ product.price }}
      
    {% endif %}
<br/><br/>
    
    Quantity:
    {% for key, value in quantities.items %}
                {% if key == product.id|slugify %}
                <option selected>{{ value }}</option>
                {% endif %}
    {% endfor %}
 

    <br/><br/>

    <strong>Total: ${{ totals }}    </strong>
    <br/><br/>
    {% endfor %}

    <a href="{% url 'cart:cart' %}" class="btn btn-primary">Cart</a>

     <br/><br/>
     <div class="card">
  <div class="card-header">
    Shipping Information
  </div>
  <div class="card-body">
    <form method="POST" action="{% url 'payment:billing_info' %}">
      {% csrf_token %}
    {{shipping_form.as_p}}
  </div>
</div>

<a href="#" class=""btn btn-success mt-3">Pay now</a>
<br/><br/>
  </div>
</div>
        </div>
            
       


{% endblock %}

ecom/payment/templates/payment/checkout.html
{% extends 'base.html' %}


{% block content %}

        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Checkout</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Review Your Order</p>
                </div>
            </div>
        </header>
        <br/>
        <div class="container">
            <div class="card">
  <div class="card-header">
    Order Summary
  </div>
  <div class="card-body">
    {% for product in cart_products %}
    {{ product.name}}
    {% if product.is_sale %}

        ${{ product.sale_price }}
    {% else %}
        {{ product.price }}
      
    {% endif %}
<br/><br/>
    
    Quantity:
    {% for key, value in quantities.items %}
                {% if key == product.id|slugify %}
                <option selected>{{ value }}</option>
                {% endif %}
    {% endfor %}
 

    <br/><br/>

    <strong>Total: ${{ totals }}    </strong>
    <br/><br/>
    {% endfor %}

    <a href="{% url 'cart:cart' %}" class="btn btn-primary">Cart</a>

     <br/><br/>
     <div class="card">
  <div class="card-header">
    Shipping Information
  </div>
  <div class="card-body">
    {{shipping_form.as_p}}
  </div>
</div>

<a href="#" class=""btn btn-success mt-3">Proceed to Payment</a>
<br/><br/>
  </div>
</div>
        </div>
            
       


{% endblock %}

ecom/payment/templates/payment/payment_success.html
<h1>Payment Successful!</h1>